### ISSUE TITLE
Extend jmx script to check file hashes

### ISSUE THREAD

**Issue by jpoolGW** [k8-proxy/aws-jmeter-test-engine-v1#28]
The following calls will need to be added;

- A call to capture the file hash from a file before it is sent to ICAP Server for processing
- A call to capture the file hash from a file after it is sent to ICAP Server for processing
- A compare assertion of the value of the original and new hash with the expected result the values are not equal

**Comment by uzfarid** [comment]
any details about how that file hash can be captured i.e where does it exist? some example would be helpful. thanks.
