### ISSUE TITLE
Implement auto scaling to automatically allocate more resource to accommodate the test load

### ISSUE THREAD

**Issue by NadHodeGW** [k8-proxy/aws-jmeter-test-engine-v1#33]

**Comment by uzfarid** [comment]
@NadHodeGW this is already implemented. Load generators are all part of auto scale group. We could ofcourse automatically create new instances if existing ones are high utilized, however, as we said before we r tuning single machine to be able to generate maximum 4k. so if someone wants 8k, then they can just ask autoscale plz give me 2, or if they want 3 then ask for 3.

**Comment by NadHodeGW** [comment]
@uzfarid , the idea of this task is to allow the automatic creation of new instances to accommodate incoming requests, so ideally we need to able to run the tests using a command without specifying the number of instances to use

**Comment by uzfarid** [comment]
@NadHodeGW is this correct understanding of your statement:  let's say I want 100k users and aws should be able automatically launch needed instances it needs to be able run that 100k ?

**Comment by NadHodeGW** [comment]
@uzfarid, yes exact

**Comment by NadHodeGW** [comment]
Implemented as required and tested, awaiting task #40 to be completed for full use
