### ISSUE TITLE
Have capability to automatically assign Ec2 instances based on any number of total users not just 4k

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/aws-jmeter-test-engine-v1#40]
this is phase 2 from https://github.com/k8-proxy/aws-jmeter-test-engine-v1/issues/33 this ticket.

Basically aim is to handle the following cases:

- total users are less than 4k. - script should create single machine. 
- total users are more than 4k, but should handle more corner cases, for example, if user wants to run 5k. then script should create 2 EC2 instances each one with 2500k users.
- in summary, for cases where total users are more than 4k, then script should ensure that there is always equal number of users are generated per EC2 instance.
- Script should create a new stack at every test run 
- Created instance name should be unique

**Comment by uzfarid** [comment]
@pranaysahith  what is difference between https://github.com/k8-proxy/aws-jmeter-test-engine-v1/pull/41 this and this ticket?

**Comment by pranaysahith** [comment]
@uzfarid #41 is the PR for this ticket.

**Comment by uzfarid** [comment]
ok. so we can close this ?

**Comment by pranaysahith** [comment]
yes, its tested and merged.
